--worlds most generic query

select *
from customer

select cname, phone  -- select command determines query columns outpput
from customer  -- from command specifies data source(s)
where cname = 'Aero Mexico';  -- filters results (basic filtering), connects tables logically

-- get the names of parts that are priced less than 200.00
select pname, price
from part
where price < 200; -- quotes are not needed for number, but for text ALWAYS use single quote for text

-- get the names of cutomers who have ordered parts from any employee who has a salary greater than 114000
select distinct customer.cname -- distinct is to erase duplicates
from customer, order1, employee  -- put every tables that is connected. Order of writing table does not matter
where customer.cno = order1.cno and order1.eno = employee.eno and employee.salary >114000; -- if same column name is used in multiple tables, put table name and . in front of the column name

-- this is the same query as above, but it uses aliases
select distinct c.cname 
from customer c, order1 o, employee e 
where c.cno = o.cno and o.eno = e.eno and e.salary >114000
order by c.cname desc;  -- order by is always the last command to execute

-- get the total number of customers
select count(cno)
from customer;


-- how many employee per department
select Dept, count(eno) [Number of Employees] --column name by using []
from employee
group by dept
--order by count(eno) asc
order by [number of employees] desc;


-- show the customer names and all revenue generated by these customers
select c.cname, sum(p.price * od.qty)
from customer c, order1 o, odetails od, part p
where c.cno = o.cno and o.ono = od.ono and od.pno = p.pno
group by c.cname;

--double check method during the quiz
select *
from part
order by price desc

select count(*)
from order1

select sum (price*qty)
from odetails, part
where 






